export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_DAY_RANGE = "GET_MOVIE_DAY_RANGE";
export const GET_PART_OF_MOVIE_LIST = "GET_PART_OF_MOVIE_LIST";
export const GET_MOVIE_INFO = "GET_MOVIE_INFO";
